spring:
  datasource:
    url: ENC(UXpBKm2vl+K5vzkZWIOW30KqUM/2Nmjq658e10IKn96XyHxlb7Z7c+FL0OlTUuP4ApQU4HrYvg0KBabiWcdKGwcf81wRquYJdaAgRJ9MNCmCm8hBX9tZstQi+pI/HBAwx9B37tW0IYodGTvWR7y2KQYTT/8pT1rx)
    username: ENC(icD4GzT+MFhPmk8Ro6C8og==)
    password: ENC(4Ul8riZqpfNtWr7yq7F3n5CcnAo5SR5E)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        default_batch_fetch_size: 1000

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
