spring:
  datasource:
    url: ENC(CptY28rV7YQickOOUYd5VOkKCv3ZMixjof2NFt51FtNrW+jmXEnpZDA/wv+f+RxdjmQK4zaN8QEOzkLh0/jloIOCGaTZ76tn+4yt5Tco4IKAtEa1esVaA9je39bWdWyj)
    username: ENC(WS0DuwNzN19hZCDcpeK0ptXS6Gv3CowQNfwGQ4A3byU=)
    password: ENC(ozxs8iZBHjljszbq6/y3cVt5Xt1Z8Nj6qh6gPobhs9A=)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 200
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
