spring:
  datasource: # todo mysql 
    url: jdbc:h2:mem:local;MODE=MySQL;DATABASE_TO_LOWER=TRUE #mysql 모드 설정
    username: sa
    password:
    driver-class-name: org.h2.Driver # todo com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
