### 멤버 생성하기 (가입하기)
POST {{host}}/public/member
Content-Type: application/json

{
    "fullName": "오예옹",
    "profileImageId": "image-id",
    "platform": "SPRING",
    "ordinal": 14,
    "gender": "FEMALE"
}

### ID 기반 멤버 로그인하기 (auth token 발급용)
GET {{host}}/public/member-login?memberId=24e5bdb9-77e7-4f51-840e-78600093e120
