### 멤버 생성하기 (가입하기)
POST {{host}}/public/member
Content-Type: application/json

{
    "fullName": "오예옹",
    "profileImageId": "image-id",
    "platform": "SPRING",
    "ordinal": 14,
    "gender": "FEMALE"
}

### ID 기반 멤버 로그인하기 (auth token 발급용)
POST {{host}}/public/member-login
Content-Type: application/json

{
    "id": "f4b610eb-aa5d-47df-bd2a-d50fd9a94d2a"
}

### 타인 프로필 조회 API
GET {{host}}/member/{{memberId}}}


### 타인 프로필 조회 Mock API
GET {{host}}/member/mock/{{memberId}}}

### 내 프로필 조회 API
GET {{host}}/member/me
Authorization: {{authorization}}

### 친구 관계 생성 API 
POST {{host}}/member/friend
Content-Type: application/json

{
    "fromMemberId": "22ee8f4c-c2db-49c5-ad5d-22db7bb67796",
    "toMemberId": "71400a62-b535-48c3-967b-5a25a64137ae"
}


### 마이스페이스 내가 받은 픽 조회 API
GET {{host}}/member/my-space/pick
Authorization: {{authorization}}
