### 내가 받은 픽 리스트 조회하기

GET {{host}}/pick/picked-list?sort=MOST_PICKED

### CREATE PICK 

POST {{host}}/pick
Content-Type: application/json

{
    "questionId": "1234564",
    "pickedId": "1"
}

### 픽 정보 오픈하기

POST {{host}}/pick/open
Content-Type: application/json

{
    "pickId": "pickId",
    "pickOpenItem": "GENDER"
}

