### 내가 받은 픽 리스트 조회하기
GET {{host}}/pick/picked-list?pageSize=10&pageNumber=0&sort=MOST_PICKED

### 내가 받은 픽 중 특정 질문의 페이징 조회하기
GET {{host}}/pick/picked-detail?questionId=abc

### CREATE PICK 

POST {{host}}/pick
Authorization: {{authorization}}
Content-Type: application/json

{
    "questionId": "3fda95ae-13af-4fb2-b872-07874c064344",
    "pickedId": "409c9126-7e69-4496-b4eb-90354ae48945",
    "questionSheetId": "b0613860-cd5b-4755-aaa3-b2d41956075a",
    "questionSetId": "2d1bdd19-c198-4df1-a4fe-f3378c4d8377"
}

### 픽 정보 오픈하기

POST {{host}}/pick/{{id}}/open
Content-Type: application/json

{
    "pickOpenItem": "GENDER"
}

### Variables
@id=1


