spring:
  application:
    name: api
  profiles:
    include: entity, common
  jackson:
    time-zone: Asia/Seoul

dojo:
  questionSet:
    size: 12
    friend-ratio: 0.6 # percent 
    open-time-1: "08:00:00"
    open-time-2: "23:00:00"
  candidate:
    size: 8
  rank:
    size: 3
  coin:
    solvedPick: 20
    adminKey1: ENC(6vmD1X1w6fIO+6hM92EYo9IF6hQIvuN2d6NSY38sjTR+SWGMdSQzueGJ/Wtkw1bd)
    adminKey2: ENC(pwjY18V7A5eWi0NAG05+aBF/VtAtMfP9v0wyuu/94ReQ6nNbuSlWQ8JgBZwCVGo2)
    adminKey3: ENC(y5CzhWOriopg+6katqbz4HtwJPPoMQfYR3Uh42LLIi8Q+ovIXXeTqonYro0JiVSq)
    adminKey4: ENC(nLz//A9qbEFOXcrcyh/Gp2PfHjcojlJxVPjXY1TBG9WKFehW6La/OWO/sVWWyHIP)
  profile:
    male: ENC(y7SDgKPyWwAg4dJMql9v7uWrAdJRQoMCHyPLxvma89kwZgpCKhva2Qi9Yfn7XBEyP6Z1hPVdfAJ4cuvcjoglQ1Obp3HtOc6+4+IXG7jttKCIA+sWpf9D3FagSvybbjN7BxgXrWIkloQ=)
    female: ENC(G6ycXZSiw82d4TkZ8q5TOGbV/PnPW5TMvBPx6a0hojXGIm3c3Ho/K5FqNBhuKl/m2pSIPzK5ammRqCCKpFw6+S8YvjrmWumC/ky6ciXrIKAbriS45RwKNuprrpnT+zyVcdf0M8VXBnI=)
    unknown: ENC(y7UKDjMVbaNQGLjGCwIWbTegx63laHRT038rGr7SH0FYmA394A14T9ber2WCFZBM4OEicjxMaME2ikQujns2nbebzVjZrNbN4OuBtA05M2ma1IF4OhDIbZaxh10i+jZ/6Ei4FCBwDB0=)
  platform:
    android: ENC(I/OtadSALKbUsJB1DqhAANHfh7PLu7A1wwEDo+OqgqtvBwAQqfREMWj8u+7dw2Ld6CPbYssh04MDzZFx4AZ5iZt3j7mmyodkcEKYNQf3aVpdyX7wMQ5WOmTR5W2NzavZ)
    design: ENC(BjL6Eg6haS9/0QJr4f9fUBXY1Ym14w9Pjn3Q5LJ6jrwpSq3dVabdWW+4JqoYYJott7vEuz1+l6hNNKCpHaKWny9gni51NHHPuR3wZtwxcP76scdub0K8usdJtAbdVecv)
    ios: ENC(7RiTeI32eGvbKA6KXzUyIPH0jM5Z2j2Q7esx/N+2Tb1J7u/zdFS3MOrf9Bibu2gOviVNQlFPdOu5JlE2sz2VWpjS8dOPFwMk/LOS7NeQgcuAVKZBIN5Tf3FW4y63W40+)
    node: ENC(U9D5eNvS4sBwicXPC/N836mw/tol3bJkW2Af3Oa4A/tBWV6m77ozjlDvFqAhG2eZcLuXwa+Ofp5jbWFfQVJTa6DF8DfWIslL0bJluzU4u3gifkq+Lr/pYD8L5L2+QXui)
    spring: ENC(27Qui/88N+zsHq25iYULFoFP2Io9Dsgfvj0lE3aCMkLprZAzWzavCVrkBXaoz2yDyZ73SbsywMOkSPucpMluTeVboM1zeIdWEAqZoqpIS5PAz0OZAQBxn0JSBrzajzYp)
    web: ENC(/VHTXuHV4/ROOCnkBGwanSTQdpJ95QKWtra9kH0kd4Mb95cI66MaD8UZuYnls5wTY01B5QBL5zV22AsRXWhQ2VhI3l4JUJCFSrCbaMMiGLhua6TGK6gJsm0hdYpAxg0R)

scheduler:
  cron: "0 0 9,21 * * *"
  sheet-cron: "0 5 9,21 * * *"

cloud:
  aws:
    cloudwatch:
      access-key: ${CLOUDWATCH_ACCESS_KEY}
      secret-key: ${CLOUDWATCH_SECRET_KEY}

