spring:
  application:
    name: api
  profiles:
    include: entity, common

dojo:
  questionSet:
    size: 12
    friend-ratio: 0.6 # percent 
    open-time-1: "08:00:00"
    open-time-2: "23:00:00"
  candidate:
    size: 8
  rank:
    size: 3

scheduler:
  cron: "0 30 2 * * *"
  sheet-cron: "0 35 2 * * *"

cloud:
  aws:
    cloudwatch:
      access-key: ${CLOUDWATCH_ACCESS_KEY}
      secret-key: ${CLOUDWATCH_SECRET_KEY}
