spring:
  application:
    name: api
  profiles:
    include: entity, common

dojo:
  questionSet:
    size: 12
    friend-ratio: 0.6 # percent 

scheduler:
  cron: "0 0 9,21 * * *"
  sheet-cron: "0 5 9,21 * * *"

cloud:
  aws:
    cloudwatch:
      access-key: ${CLOUDWATCH_ACCESS_KEY}
      secret-key: ${CLOUDWATCH_SECRET_KEY}
      
